### ISSUE TITLE
Melhorar navegabilidade desses componentes

### ISSUE THREAD

**Issue by joacir** [Massau/AelianTreinamento#13]
Melhorar a navegabilidade dos botões dessa linha, talvez seja melhor pro usuário visualiza-los acima da tabela e manter os controles de paginação logo abaixo da tabela.

https://github.com/Massau/AelianTreinamento/blob/54620858e3217cd5fecc1e51377c237b5ea7dd4b/consulta.html#L96

**Comment by Massau** [comment]
Foi _reordenado_ o código de maneira aos botões ficarem acima da tabela, com a paginação abaixo.

Havia também um _fechamento de tag a mais_, cujo comentário indicava ser referente à uma div cuja class era "col-md-10 col-lg-10", porém provavelmente era residual de uma coluna que foi removida do código.
