### ISSUE TITLE
Evitar usar nova classe para estilo das fontes

### ISSUE THREAD

**Issue by joacir** [Massau/AelianTreinamento#3]
Tentar utilizar o máximo possível a tipografia do bootstrap:

Conforme especificação: https://getbootstrap.com/docs/4.1/content/typography/

https://github.com/Massau/AelianTreinamento/blob/54620858e3217cd5fecc1e51377c237b5ea7dd4b/index.html#L63

https://github.com/Massau/AelianTreinamento/blob/master/index.html#L63

**Comment by Massau** [comment]
Foram utilizadas as classes relativas à cores da fonte, próprias do framework Bootstrap, como _.text-danger_ para estilizar a tipografia.
