### ISSUE TITLE
Faltou form-group

### ISSUE THREAD

**Issue by joacir** [Massau/AelianTreinamento#4]
Para um melhor aproveitamento do bootstrap, é preciso agrupar os campos do formulários com uma div de classe "form-group". 

Também faltou atribuir a classe "form-control" para a input.

Conforme documentação (https://getbootstrap.com/docs/4.1/components/forms/)

https://github.com/Massau/AelianTreinamento/blob/54620858e3217cd5fecc1e51377c237b5ea7dd4b/index.html#L67

**Comment by Massau** [comment]
Foram utilizados o _Form-group_  bem como a classe _Form-control,_ para melhor aproveitamento, conforme foi mencionado
