### ISSUE TITLE
Quabra de linha no lugar do form-group

### ISSUE THREAD

**Issue by joacir** [Massau/AelianTreinamento#5]
Não precisaria do "br" se agruparmos os campos com a div "form-group".

https://github.com/Massau/AelianTreinamento/blob/54620858e3217cd5fecc1e51377c237b5ea7dd4b/index.html#L68

**Comment by Massau** [comment]
Após utilizar do _Form-group_ para agrupar os conteúdos foram removidas quebras de linha desnecessárias
