### ISSUE TITLE
Radio não esta usando bootstrap

### ISSUE THREAD

**Issue by joacir** [Massau/AelianTreinamento#6]
Substituir o "h6" por label e tentar utilizar as ferramentas do bootstrap para padronizar o comportamento do fomulário.

Conforme documentado: https://getbootstrap.com/docs/4.1/components/forms/#checkboxes-and-radios

https://github.com/Massau/AelianTreinamento/blob/54620858e3217cd5fecc1e51377c237b5ea7dd4b/index.html#L73

**Comment by Massau** [comment]
Estava utilizando _checkbox_ para um campo que necessita uma resposta assertiva, sendo 'Sim' ou 'Não. checkbox foi substituído por _radio,_ utilizando classes do Bootstrap
